apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: canal
  namespace: kube-system
spec:
  valuesContent: |-
    # The IPv4 cidr pool to create on startup if none exists. Pod IPs will be
    # chosen from this range.
    podCidr: "10.42.0.0/16"

    flannel:
      iface: ""
      backend: "vxlan"
      